# Generated by Django 5.0.6 on 2026-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_branch_companysettings_coursecategory_leadsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_intent',
            field=models.CharField(blank=True, default='General Enquiry', max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_next_action',
            field=models.CharField(blank=True, default='Call to introduce course details', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_suggested_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
