# Generated by Django 5.0.6 on 2026-09-13 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_ai_intent_lead_ai_next_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_result',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('NOT_CONNECTED', 'Not Connected'), ('BUSY', 'Busy'), ('SWITCHED_OFF', 'Switched Off'), ('WRONG_NUMBER', 'Wrong Number'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('CALLBACK_REQUESTED', 'Call Back Requested 📞'), ('CONVERTED', 'Converted 🎉')], default='CONNECTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('CALL_BACK', 'Call Back 📞'), ('CONVERTED', 'Converted'), ('DROPPED', 'Dropped'), ('BUSY', 'Busy'), ('NOT_CONNECTED', 'Not Connected'), ('SWITCHED_OFF', 'Switched Off'), ('WRONG_NUMBER', 'Wrong Number')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='AllocationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=150, unique=True)),
                ('lead_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allocations', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_batches', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_batches', to='leads.importbatch')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='allocation_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.allocationbatch'),
        ),
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
    ]
