# Generated by Django 5.0.6 on 2026-09-13 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_assigned_at_user_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.branch'),
        ),
        migrations.AddField(
            model_name='lead',
            name='requirement_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_result',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('NOT_CONNECTED', 'Not Connected'), ('BUSY', 'Busy'), ('SWITCHED_OFF', 'Switched Off'), ('WRONG_NUMBER', 'Wrong Number'), ('INVALID_NUMBER', 'Invalid Number'), ('NO_RESPONSE', 'No Response'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('CALLBACK_REQUESTED', 'Call Back Requested 📞'), ('CONVERTED', 'Converted 🎉')], default='CONNECTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('CALL_BACK', 'Call Back 📞'), ('CONVERTED', 'Converted'), ('DROPPED', 'Dropped'), ('BUSY', 'Busy'), ('NOT_CONNECTED', 'Not Connected'), ('SWITCHED_OFF', 'Switched Off'), ('WRONG_NUMBER', 'Wrong Number'), ('INVALID_NUMBER', 'Invalid Number'), ('NO_RESPONSE', 'No Response')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(default='Lead Dataset Export', max_length=100)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('record_count', models.IntegerField(default=0)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
    ]
