# Generated by Django 5.0.6 on 2026-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_budget_lead_preferred_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
