# Generated by Django 5.0.6 on 2026-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_calllog_call_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_response',
            field=models.CharField(blank=True, default='Not Contacted', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_call_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_result',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('NOT_CONNECTED', 'Not Connected'), ('NOT_ANSWERED', 'Not Answered 📵'), ('BUSY', 'Busy'), ('SWITCHED_OFF', 'Switched Off'), ('WRONG_NUMBER', 'Wrong Number'), ('INVALID_NUMBER', 'Invalid Number'), ('NO_RESPONSE', 'No Response'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('CALLBACK_REQUESTED', 'Call Back Requested 📞'), ('CONVERTED', 'Converted 🎉')], default='CONNECTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('CALL_BACK', 'Call Back 📞'), ('CONVERTED', 'Converted'), ('DROPPED', 'Dropped'), ('BUSY', 'Busy'), ('NOT_ANSWERED', 'Not Answered 📵'), ('NOT_CONNECTED', 'Not Connected'), ('SWITCHED_OFF', 'Switched Off'), ('WRONG_NUMBER', 'Wrong Number'), ('INVALID_NUMBER', 'Invalid Number'), ('NO_RESPONSE', 'No Response')], default='NEW', max_length=30),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['contacted'], name='leads_lead_contact_147c15_idx'),
        ),
    ]
