# Generated by Django 5.2.17 on 2026-09-14 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_securityauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True)),
                ('daily_call_target', models.IntegerField(default=30)),
                ('daily_conversion_target', models.IntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-target_date', 'caller'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['scheduled_date'], name='leads_lead_schedul_8eddd6_idx'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='caller',
            field=models.ForeignKey(limit_choices_to={'role': 'TELECALLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyschedule',
            unique_together={('caller', 'target_date')},
        ),
    ]
