# Generated by Django 5.0.6 on 2026-09-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_dailyschedule_lead_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_whatsapp_message',
            field=models.TextField(blank=True, default='Hi {{name}} 👋\n\nGood day from {{company_name}}!\n\nThank you for your interest in our {{course}}.\n\n📚 Course: {{course}}\n🏢 Branch: {{branch}}\n\nI can share the complete:\n• Course details\n• Syllabus\n• Duration\n• Fees\n• Upcoming batch details\n\nPlease let me know if you would like the details. 😊\n\nRegards,\n{{caller_name}}'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='action',
            field=models.CharField(choices=[('USERNAME_CHANGED', 'Username Changed'), ('PASSWORD_CHANGED', 'Password Changed'), ('TELECALLER_CREATED', 'Telecaller Created'), ('OTHER_SESSIONS_LOGGED_OUT', 'Other Sessions Logged Out'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=50),
        ),
    ]
