# Generated by Django 5.0.6 on 2026-09-30 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_companysettings_default_whatsapp_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(default=django.utils.timezone.now)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('total_assigned', models.IntegerField(default=0)),
                ('total_calls_attempted', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('interested_count', models.IntegerField(default=0)),
                ('call_back_count', models.IntegerField(default=0)),
                ('not_answered_count', models.IntegerField(default=0)),
                ('not_interested_count', models.IntegerField(default=0)),
                ('busy_count', models.IntegerField(default=0)),
                ('switched_off_count', models.IntegerField(default=0)),
                ('connected_count', models.IntegerField(default=0)),
                ('wrong_number_count', models.IntegerField(default=0)),
                ('invalid_number_count', models.IntegerField(default=0)),
                ('no_response_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telecaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletedWorkflowLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('attempts_in_workflow', models.IntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workflows', to='leads.lead')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_leads', to='leads.completedworkflow')),
            ],
            options={
                'ordering': ['-workflow__created_at'],
            },
        ),
    ]
